# Generated by Django 4.2.21 on 2025-09-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "__first__"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("OWNER", "Owner"),
                    ("COACH", "Coach"),
                    ("CLIENT", "Client"),
                ],
                default="CLIENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.tenant",
            ),
        ),
    ]
